print ("Hello! Welcome to the land of Chronos.")
srt =input ("You are an adventure! Want to start your adventure? (Please say \"Yes\") ")
if srt == ("Yes"):
    print ("Let's start our adventure!")
    print ("You are a weary soldier traveling back home from the war.")
    print ("You stop at a bar in a small shanty town.")
    print ("Bartender: 'Hi stranger, what do you want?' ")
    print ("Hey, it's me the game. Say if you want a \"beer\" or \"milk\". ")
    drnk = input ("Okay I'll have a ")
    if drnk==("beer"):
        print("Damn, you're a man!")
    if drnk==("milk"):
        print ("What a soyboy!")
    print ("'What's your name?' asks the Bartender.")
    name = input("My name is ")
    print ("Well "+name+", hope you enjoy that glass of "+drnk+".")
    print ("Whilst rinking your tall glass of "+drnk+",")
    print ("you notice a small boy asking for help.")
    hlpbrd=input("Should we help him? (Answer \"Yes\" please!) ")
    if hlpbrd==("Yes"):
        print ("You walk over to Brad and tell him you can offer your assisstance.")
        print ("The small child seemed overjoyed that someone had finally offered.")
        print ("He says is name is Brad, and that you need to save his parents!")
        print ("You gather your braodsword and shuffle out, following the sound")
        print ("of Brad's small feet.")
        print ("You hear the bartender call out 'Good luck, "+name+"!'")
        print ("You learn during the walk with Brad that his parents are held")
        print ("captive by the King.")
        md=input("Should you save Mom or Dad first? (Type \"Mom\" or \"Dad.\") ")
        if md == ("Dad"):
            print("You fight towards the male wing of he prison.")
            print("You see a disheveled man hunched in a corner.")
            print("Brad runs toward him. ")
            print("His father leaves, and asks about his wife. The guards are coming, so you have to leave.")
            print("You leave without his mom.")
            print("'How can I repay you?' asks the Dad.")
            rwrd = input ("Do you want money? (Answer \"Yes\" or \"No\" please!) ")
            if rwrd == ("Yes"):
                print ("The Dad scrounges up 500 gold coins from under the floorboards.")
                print ("He hands them to you.")
                print ("YOU HAVE GAINED 500 GOLD COINS.")
            if rwrd == ("No"):
                print ("Then I will make Brad your apprentice. I entrust him to you.")
                
        if md == ("Mom"):
            print ("You fight a few guards and head to the female wing.")
            print ("Despite this, Brad wants you to find his dad first.")
            print ("You find a disheveled lady, who Brad recognizes as his mother.")
            print ("'Mom' he calls out. The figure lifts their head.")
            print ("You pick her up and leave.")
            print ("You return two months later to find Brad starved and his mother")
            print ("malnourishing him to feed herself.")
            print ("There is nothing you can do. The End.")
    else:
        print ("You shift back in your seat, and ignore the nuisance.")
        print ("You see a hooded figure enter the bar.")
        print ("You glance a few golden curls, and deep blue eyes as they walk past you.")
        print ("A few minutes later, castle guards appear.")
        print ("They are looking for a blonde, female child.")
        print ("Urged by your apathy beforehand, you decide to help.")
        hlplcy=input("Do we \"hide\" her? (\"Yes\" or \"No\") ")
        if hlplcy == ("Yes"):
            print ("You inconspicuously leave and find the figure.")
            print ("You realize that the small girl is scared.")
            print ("You decide to usher her into a sideroom.")
            print ("While talking to her, you learn her name is Lucy.")
            print ("In progress...")
else:
    print("Oh well.")